#dist: trusty
language: php

php:
    - 7.1
    - 7.2
    - 7.3
#  - hhvm

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

script: phpunit --coverage-text
