sf4_api_user_locale_detail:
    path: /detail/{id}/{token}
    methods: [GET, OPTIONS]

sf4_api_user_locale_list:
    path: /list/{token}
    methods: [GET, POST, OPTIONS]

sf4_api_user_locale_save_detail:
    path: /save/{id}/{token}
    methods: [POST, OPTIONS]
